### ISSUE TITLE
CF Application not starting

### ISSUE THREAD

**Issue by sergioRozenszajn** [yharish991/openresty-buildpack#1]
Hi,
I'm trying to push an app with this buildpack to CF. It contains the example from openResty:
worker_processes 2;
pid logs/nginx.pid;
daemon off;

events {
   worker_connections 768;
}
http{
   server{
      location /lua {
		 content_by_lua_block {
			 local mydata = require "mydata"
			 ngx.say(mydata.get_age("dog"))
		 }
      }
   }
}

The application start fails with:
ERR nginx: [alert] could not open error log file: open() "/tmp/app/openresty/nginx/logs/error.log" failed (2: No such file or directory)
unknown directive "content_by_lua_block" in /home/vcap/app/openresty/nginx/conf/nginx.conf:11
Can you advise?
Thanks, Sergio

**Comment by yharish991** [comment]
@sergioRozenszajn I updated the latest version of the buildpack, please try and let me know if it still doesn't work.

**Comment by sergioRozenszajn** [comment]
After pushing I get the message:
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
Like it does not manage to start however the logs don't show any error.

When I look into the apps with cf apps it looks like the app is started correctly.
I've attached my simple app as a reference.

[html5-apps-repo-rt-lua.zip](https://github.com/yharish991/openresty-buildpack/files/1294840/html5-apps-repo-rt-lua.zip)

**Comment by sergioRozenszajn** [comment]
No, sorry, it is not really working. It crashed:
ERR Failed to make TCP connection to port 8080: connection refused
2017-09-12T09:02:15.73+0300 [CELL/0]     ERR Timed out after 1m0s: health check never passed.

**Comment by yharish991** [comment]
Read the comments i put in the nginx.conf

```worker_processes 2;
pid logs/nginx.pid;
daemon off;
error_log <%= ENV["APP_ROOT"] %>/nginx/logs/error.log error; // also you need to specify the error.log path
events {
   worker_connections 768;
}
http{
  lua_package_path <%= ENV["APP_ROOT"]%>/scripts/lua-scripts/?.lua; // you need to set the lua package path like this
   server{
      location /lua {
		 content_by_lua_block {
			 local mydata = require "mydata"
			 ngx.say(mydata.get_age("dog"))
		 }
    }
  }
}
```

**Comment by sergioRozenszajn** [comment]
Still failing. I'm not sure what you mean with the error.log path in root/logs
my nginx.conf looks like this:
pid logs/nginx.pid;
daemon off;
error_log <%= ENV["APP_ROOT"] %>/nginx/logs/error.log error;
events {
   worker_connections 768;
}
http{
  lua_package_path <%= ENV["APP_ROOT"]%>/scripts/lua-scripts/mydata.lua;
   server{
      location /lua {
		 content_by_lua_block {
			 local mydata = require "mydata"
			 ngx.say(mydata.get_age("dog"))
		 }
    }
  }
}

**Comment by sergioRozenszajn** [comment]
It works!!
I missed the following in nginx.conf
server{
      listen <%= ENV["PORT"] %> ;
      server_name localhost;
Is this project related to the standard staticfile buildpack from CF?. Is it expected to be released as an open source?
Thank you, Sergio

**Comment by yharish991** [comment]
As i now i don't have any intentions of making it open source, but feel free to make PR for enhancements.
